# Generated by Django 5.2.10 on 2026-03-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "customers",
            "0002_remove_customer_address_customer_city_customer_state_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="street",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
