# Generated by Django 5.2.10 on 2026-03-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_alter_customer_city_alter_customer_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="street",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="zip_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
